2025-01-28 11:37:33,793 - INFO - Sistema iniciado com sucesso.
2025-01-28 11:37:36,997 - INFO - Sistema iniciado com sucesso.
2025-01-28 11:39:51,342 - INFO - Sistema iniciado com sucesso.
2025-01-28 11:40:06,061 - INFO - Sistema iniciado com sucesso.
2025-01-28 11:41:03,311 - INFO - Sistema iniciado com sucesso.
2025-01-28 11:41:52,466 - INFO - Sistema iniciado com sucesso.
2025-01-28 11:42:13,458 - INFO - Sistema iniciado com sucesso.
2025-01-28 13:49:31,972 - INFO - Sistema iniciado com sucesso.
2025-01-28 13:54:44,976 - INFO - Sistema iniciado com sucesso.
2025-01-28 13:54:47,801 - INFO - Sistema iniciado com sucesso.
2025-01-28 13:58:33,582 - INFO - Sistema iniciado com sucesso.
2025-01-28 13:58:36,513 - INFO - Sistema iniciado com sucesso.
2025-01-28 16:00:54,447 - INFO - Sistema iniciado com sucesso.
2025-01-28 16:00:57,504 - INFO - Sistema iniciado com sucesso.
2025-01-29 16:50:33,471 - INFO - Sistema iniciado com sucesso.
2025-01-29 16:50:36,889 - INFO - Sistema iniciado com sucesso.
2025-01-29 17:00:57,242 - INFO - Sistema iniciado com sucesso.
2025-01-30 08:40:21,071 - INFO - Sistema iniciado com sucesso.
2025-01-30 08:40:24,204 - INFO - Sistema iniciado com sucesso.
2025-01-30 08:53:05,923 - INFO - Sistema iniciado com sucesso.
2025-01-30 08:56:49,566 - INFO - Sistema iniciado com sucesso.
2025-01-30 09:18:00,699 - INFO - Sistema iniciado com sucesso.
2025-01-30 09:22:24,843 - INFO - Sistema iniciado com sucesso.
2025-01-30 09:26:06,720 - INFO - Sistema iniciado com sucesso.
2025-01-30 09:33:05,337 - INFO - Sistema iniciado com sucesso.
2025-01-30 09:41:13,346 - INFO - Sistema iniciado com sucesso.
2025-01-30 11:54:30,213 - INFO - Sistema iniciado com sucesso.
2025-01-30 11:54:38,410 - ERROR - Exception on /pg/cob [POST]
Traceback (most recent call last):
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\WNB\OneDrive - Wireless Networks do Brasil LTDA\Área de Trabalho\API Pix\modules\plugin_chrome_modules\routes.py", line 31, in cob_imediata_post_pg
    return jsonify(response.json), response.status_code
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
2025-01-30 11:54:52,024 - ERROR - Exception on /pg/cob [POST]
Traceback (most recent call last):
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\WNB\OneDrive - Wireless Networks do Brasil LTDA\Área de Trabalho\API Pix\modules\plugin_chrome_modules\routes.py", line 31, in cob_imediata_post_pg
    return jsonify(response.json), response.status_code
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
2025-01-30 11:58:11,731 - ERROR - Exception on /pg/cob [POST]
Traceback (most recent call last):
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\WNB\OneDrive - Wireless Networks do Brasil LTDA\Área de Trabalho\API Pix\modules\plugin_chrome_modules\routes.py", line 31, in cob_imediata_post_pg
    return jsonify(response.json), response.status_code
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
2025-01-30 12:01:27,404 - ERROR - Exception on /pg/cob [POST]
Traceback (most recent call last):
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\WNB\OneDrive - Wireless Networks do Brasil LTDA\Área de Trabalho\API Pix\modules\plugin_chrome_modules\routes.py", line 31, in cob_imediata_post_pg
    return jsonify(response.json), response.status_code
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
2025-01-30 12:01:47,731 - INFO - Sistema iniciado com sucesso.
2025-01-30 12:02:07,957 - ERROR - Exception on /pg/cob [POST]
Traceback (most recent call last):
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\WNB\OneDrive - Wireless Networks do Brasil LTDA\Área de Trabalho\API Pix\modules\plugin_chrome_modules\routes.py", line 31, in cob_imediata_post_pg
    return jsonify(response.json), response.status_code
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
2025-01-30 12:03:31,190 - ERROR - Exception on /pg/cob [POST]
Traceback (most recent call last):
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\WNB\OneDrive - Wireless Networks do Brasil LTDA\Área de Trabalho\API Pix\modules\plugin_chrome_modules\routes.py", line 31, in cob_imediata_post_pg
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
2025-01-30 12:04:23,825 - ERROR - Exception on /pg/cob [POST]
Traceback (most recent call last):
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\WNB\OneDrive - Wireless Networks do Brasil LTDA\Área de Trabalho\API Pix\modules\plugin_chrome_modules\routes.py", line 31, in cob_imediata_post_pg
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\wnb\appdata\local\programs\python\python38\lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
2025-01-30 14:29:39,970 - INFO - Sistema iniciado com sucesso.
2025-01-30 14:50:07,403 - INFO - Sistema iniciado com sucesso.
